name: Salesforce Validation and Deployment

on:
  pull_request:
       types: [closed]

jobs:
  validate_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Salesforce Authentication
      run: |
        sfdx force:auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY_DEV}} --username ${{ secrets.SFDC_DEV_USER}} --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl https://test.salesforce.com

    - name: Validate on Salesforce
      run: |
        sfdx force:source:deploy -u ${{ secrets.SFDC_DEV_USER}} --checkonly --testlevel RunLocalTests -x ./manifest/package.xml

    - name: Deploy to Techmerge
      run: |
        sfdx force:source:deploy -u your-org-name -p force-app/main/default -x ./manifest/package.xml
