name: Salesforce Validation and Deployment

on:
  pull_request:
       types: [closed]

jobs:
  validate_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true

      - name: Install CLI
        run: |
             npm install sfdx-cli --global
             echo "La branch di partenza è ${{ github.head_ref }}"
             echo "La branch di arrivo è ${{ github.base_ref }}"
       
      - name: Authentication in Tech-Merge
        if: ${{ github.base_ref == 'tech-merge' }}
        run: |
             sfdx force:auth:jwt:grant --clientid ${{secrets.CONSUMER_KEY_TMERGE}}  --username ${{secrets.SFDC_TMERGE_USER}} --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl https://test.salesforce.com
             name: Validate on Salesforce
             run: |
                  sfdx force:source:deploy -u ${{secrets.SFDC_TMERGE_USER}} --checkonly --testlevel RunLocalTests -x ./manifest/package.xml
      
      - name: Authentication in PreProd
        if: ${{ github.base_ref == 'preprod' }}
        run: |
             sfdx force:auth:jwt:grant --clientid ${{secrets.CONSUMER_KEY_PREPROD}}  --username ${{secrets.SFDC_PREPROD_USER}} --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl https://test.salesforce.com
             name: Validate on Salesforce
             run: |
                  sfdx force:source:deploy -u ${{secrets.SFDC_PREPROD_USER}} --checkonly --testlevel RunLocalTests -x ./manifest/package.xml
      
      #- name: Validate on Salesforce
        #run: |
        # sfdx force:source:deploy -u ${{secrets.SFDC_TMERGE_USER}} --checkonly --testlevel RunLocalTests -x ./manifest/package.xml

#- name: Deploy to Techmerge
 #       run: |
  #        sfdx force:source:deploy -u ${{ secrets.SFDC_PROD_USER}} -x ./manifest/package.xml
