name: Validazione e Deployment

on:
  pull_request:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [dev1, techmerge, preprod, prod]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Validate
      if: ${{ matrix.branch != 'prod' }}
      run: npm run validate

    - name: Deploy
      if: ${{ matrix.branch != 'prod' }}
      run: npm run deploy
