name: Validate and Deploy

on:
  push:
    branches:
      - dev1
      - techmerge
      - preprod
  pull_request:
    branches:
      - dev1
      - techmerge
      - preprod
      - prod

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [my-dev-org, my-prod-org]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate code
        run: sfdx force:source:deploy -x ./manifest/FirstTestDeploy.xml -c -u ${{ matrix.org }} -w 10 --checkonly
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/prod' }}
      - name: Deploy code
        run: sfdx force:source:deploy -x ./manifest/FirstTestDeploy.xml -u ${{ matrix.org }} -w 10
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/prod' }}
